export type DeliveryZone = 1 | 2 | 3 | 4 | 5;

export const WILAYA_ZONES: Record<string, DeliveryZone> = {
  DZ01: 5, DZ02: 2, DZ03: 4, DZ04: 3, DZ05: 3, DZ06: 2, DZ07: 3, DZ08: 5,
  DZ09: 1, DZ10: 2, DZ11: 5, DZ12: 3, DZ13: 3, DZ14: 3, DZ15: 2, DZ16: 1,
  DZ17: 4, DZ18: 2, DZ19: 2, DZ20: 3, DZ21: 2, DZ22: 3, DZ23: 2, DZ24: 3,
  DZ25: 2, DZ26: 2, DZ27: 2, DZ28: 3, DZ29: 3, DZ30: 4, DZ31: 2, DZ32: 4,
  DZ33: 5, DZ34: 2, DZ35: 1, DZ36: 2, DZ37: 5, DZ38: 3, DZ39: 4, DZ40: 3,
  DZ41: 2, DZ42: 1, DZ43: 2, DZ44: 2, DZ45: 4, DZ46: 3, DZ47: 4, DZ48: 3,
  DZ49: 5, DZ50: 4, DZ51: 3, DZ52: 5, DZ53: 5, DZ54: 4, DZ55: 5, DZ56: 5,
  DZ57: 5, DZ58: 5,
};

export const WILAYA_LIST: Array<{ code: string; name: string }> = [
  { code: "DZ01", name: "Adrar" },
  { code: "DZ02", name: "Chlef" },
  { code: "DZ03", name: "Laghouat" },
  { code: "DZ04", name: "Oum El Bouaghi" },
  { code: "DZ05", name: "Batna" },
  { code: "DZ06", name: "Béjaïa" },
  { code: "DZ07", name: "Biskra" },
  { code: "DZ08", name: "Béchar" },
  { code: "DZ09", name: "Blida" },
  { code: "DZ10", name: "Bouira" },
  { code: "DZ11", name: "Tamanrasset" },
  { code: "DZ12", name: "Tébessa" },
  { code: "DZ13", name: "Tlemcen" },
  { code: "DZ14", name: "Tiaret" },
  { code: "DZ15", name: "Tizi Ouzou" },
  { code: "DZ16", name: "Alger" },
  { code: "DZ17", name: "Djelfa" },
  { code: "DZ18", name: "Jijel" },
  { code: "DZ19", name: "Sétif" },
  { code: "DZ20", name: "Saïda" },
  { code: "DZ21", name: "Skikda" },
  { code: "DZ22", name: "Sidi Bel Abbès" },
  { code: "DZ23", name: "Annaba" },
  { code: "DZ24", name: "Guelma" },
  { code: "DZ25", name: "Constantine" },
  { code: "DZ26", name: "Médéa" },
  { code: "DZ27", name: "Mostaganem" },
  { code: "DZ28", name: "M'Sila" },
  { code: "DZ29", name: "Mascara" },
  { code: "DZ30", name: "Ouargla" },
  { code: "DZ31", name: "Oran" },
  { code: "DZ32", name: "El Bayadh" },
  { code: "DZ33", name: "Illizi" },
  { code: "DZ34", name: "Bordj Bou Arréridj" },
  { code: "DZ35", name: "Boumerdès" },
  { code: "DZ36", name: "El Tarf" },
  { code: "DZ37", name: "Tindouf" },
  { code: "DZ38", name: "Tissemsilt" },
  { code: "DZ39", name: "El Oued" },
  { code: "DZ40", name: "Khenchela" },
  { code: "DZ41", name: "Souk Ahras" },
  { code: "DZ42", name: "Tipaza" },
  { code: "DZ43", name: "Mila" },
  { code: "DZ44", name: "Aïn Defla" },
  { code: "DZ45", name: "Naâma" },
  { code: "DZ46", name: "Aïn Témouchent" },
  { code: "DZ47", name: "Ghardaïa" },
  { code: "DZ48", name: "Relizane" },
  { code: "DZ49", name: "Timimoun" },
  { code: "DZ50", name: "Bordj Badji Mokhtar" },
  { code: "DZ51", name: "Ouled Djellal" },
  { code: "DZ52", name: "Béni Abbès" },
  { code: "DZ53", name: "In Salah" },
  { code: "DZ54", name: "In Guezzam" },
  { code: "DZ55", name: "Touggourt" },
  { code: "DZ56", name: "Djanet" },
  { code: "DZ57", name: "El M'Ghair" },
  { code: "DZ58", name: "El Meniaa" },
];

export const WILAYA_NAMES: Record<string, string> = Object.fromEntries(
  WILAYA_LIST.map((w) => [w.code, w.name]),
);
